### PR TITLE
[HttpServer] Update the docs to reference the new web messages

### PR DESCRIPTION
**Pull request by nikmd23**
This merging this PR will complete Glimpse/Messages#1

It is currently on hold, as we wait for Glimpse/Messages#8 to be merged.

### CODE REVIEW

**Comment by philliphoff** [comment]
Looks ok; should I just cancel/close my previous PR for this?

**Comment by avanderhoorn** [comment]
I think @nikmd23 might have missed the previous PR you did?

**Comment by nikmd23** [comment]
Doh! Yeah, that other PR isn't assigned to a milestone of pipeline or anything, so I totally missed it. Sorry to duplicate effort.

**Comment by philliphoff** [comment]
No worries, it was a pretty minimal change.

**Pull request merged**
